### ISSUE TITLE
Suggestion for the location of binary .jar file

### ISSUE THREAD

**Issue by shenwei356** [CJ-Chen/TBtools#1]
Hi @CJ-Chen,

If you'd like to just release binary files and you may update versions frequently,
a better way is publishing it at [release page](https://github.com/CJ-Chen/TBtools/releases)

Otherwise, the size of `.git` directory will increase a lot with new version, 
because `git` tracks all the file changes.

Wei

**Comment by CJ-Chen** [comment]
Thx for your suggestion...
