### ISSUE TITLE
陈老师您好，我用tbtools做go注释发现结果与其他的不一样

### ISSUE THREAD

**Issue by life333** [CJ-Chen/TBtools#10]
一个基因，我用了默认的参数，在tbtools跑，go注释发现对应100多个go条目，但是在interpro里面才找到2个

**Comment by CJ-Chen** [comment]
恩，你换个工具又会得到一个结果。可以试试。比较比较。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yangyang <notifications@github.com&gt;
发送时间: 2020年11月13日 18:44
收件人: CJ-Chen/TBtools <TBtools@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[CJ-Chen/TBtools] 陈老师您好，我用tbtools做go注释发现结果与其他的不一样 (#10)





 
一个基因，我用了默认的参数，在tbtools跑，go注释发现对应100多个go条目，但是在interpro里面才找到2个

**Comment by life333** [comment]
好的，谢谢老师
