### ISSUE TITLE
MEME motif can not be aligned 

### ISSUE THREAD

**Issue by Zefeng-Wu** [CJ-Chen/TBtools#13]
After I obtain the xml result from MEME suit, I want to visualize the motif distribution. TBtools is a good plotter, but I want to align the same motif in different sequences to keep them in the same relative position, e.g. by setting all the sequences as the same length. Can the software do this?
Besides, I noticed that the default result in MEME result ONLY show those true motif but without the predicted motifs. However, JC tools output all the motifs including true motif and predicted motif in the output. Can it be set?

**Comment by CJ-Chen** [comment]
have not supported yet.
