### ISSUE TITLE
GO enrichment question

### ISSUE THREAD

**Issue by fayweili** [CJ-Chen/TBtools#16]
Hi, 

I noticed the results are different between for example, `*MF_EnrichResult.xls.sorted.padjust.xls` and `*.GO.Enrichment.final.xls`. Was there a filtering step from MF to final? If so how was this done? Thanks!!

Fay-Wei

**Comment by CJ-Chen** [comment]
Yes,  pValue<=0.05 and hitSizeInSelectedSet>=5. 
Join our telegram group for more details.
