### ISSUE TITLE
MCSanX wrapper result showing zero collinear genes:

### ISSUE THREAD

**Issue by GK0745** [CJ-Chen/TBtools#17]
After performing soybean protein blast in BLAST GUI wrapper and converting GFF file to SimGxf, I have tried to run MCScanX wrapper, but the collinearity files show zero results.
I did check the transcript ID of both blast and SimGxf files both share the same ID. I am attaching those files.
Can you please guide me on where I am going wrong  so that I can finish this project?
[Gm.zip](https://github.com/CJ-Chen/TBtools/files/5931816/Gm.zip)

**Comment by CJ-Chen** [comment]
You have uploaded two blast files. Please re-check your gff file.

**Comment by GK0745** [comment]
Thank you.
