### ISSUE TITLE
输出档GO.Enrichment.final.xls没有列出基因 (引用#23)

### ISSUE THREAD

**Issue by hungweichen0327** [CJ-Chen/TBtools#24]
陈博士您好：

不好意思上一篇议题关闭了，所以我开一个新的议题。(引用#23)
我在「TBtools」参考手册搜寻了Go enrichment相关资料后，并没有找到解决办法。我有参照手册上所写的操作，但还是遇到一样的问题。
附件是我操作TBtools 开始执行Go enrichment前的介面，以及Debug_log的资讯。

![TBtools_interface](https://user-images.githubusercontent.com/54091758/138662535-8f4d99d4-ab84-4117-beb1-7eae327eded9.png)
[Debug_log.txt](https://github.com/CJ-Chen/TBtools/files/7408515/Debug_log.txt)

谢谢您！

**Comment by CJ-Chen** [comment]
从运行信息来看，你使用了背景注释中所有基因作为选择集，这个是不会有富集分析结果的。请了解下相关方面，即 基因集合功能富集分析 方面的内容。
