### ISSUE TITLE
demo data can't be downloaded!

### ISSUE THREAD

**Issue by Chipcui** [CJ-Chen/TBtools#25]
Hi,

The demo data can't be downloaded anymore, and there's any other methods to get it?

Thank you!

**Comment by CJ-Chen** [comment]
That server is down. Those demo data is missing. Usage of all functions please refer to the TBtools Cookbook.
《TBtools Cookbook》 - 写给「TBtools」所有用户的参考手册 https://www.yuque.com/cjchen/hirv8i
你想知道的，都在里面了：
1. 软件/数据库的下载/更新
2. 对应功能的使用说明与具体示例
3. 常见问题 FAQ 及解决方案
4. 如何有效提出 TBtools 使用问题从而快速获得回复并得到解决

**Comment by CHENCANcc** [comment]
可以在github上分享一下吗，有demo data会帮助理解很多
谢谢！
