### ISSUE TITLE
求0.58版本

### ISSUE THREAD

**Issue by Clovecookie** [CJ-Chen/TBtools#3]
不知道还有没有？

**Comment by CJ-Chen** [comment]
没有。旧的版本或者功能太少，或者含有废弃功能。现在只有最新版

**Comment by Clovecookie** [comment]
好的，谢谢，目前已经了解到最新版也可以用了，之前是导师指定的旧版本


 
---原始邮件---
发件人: "CJ-Chen"<notifications@github.com>
发送时间: 2019年5月8日(星期三) 上午8:33
收件人: "CJ-Chen/TBtools"<TBtools@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"Clovecookie"<835138001@qq.com>;
主题: Re: [CJ-Chen/TBtools] 求0.58版本 (#3)



没有。旧的版本或者功能太少，或者含有废弃功能。现在只有最新版

**Comment by CJ-Chen** [comment]
恩....如果新的版本不能用，那么可以提出。旧的版本我就不关心bux fixing了 
------------------
===============================
CJchenhttp://cj-chen.github.io/


 




------------------ 原始邮件 ------------------
发件人: "Clovecookie"<notifications@github.com>; 
发送时间: 2019年5月8日(星期三) 上午8:34
收件人: "CJ-Chen/TBtools"<TBtools@noreply.github.com>; 
抄送: "CJ"<120509419@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [CJ-Chen/TBtools] 求0.58版本 (#3)



好的，谢谢，目前已经了解到最新版也可以用了，之前是导师指定的旧版本 
 
 
   
 ---原始邮件--- 
 发件人: "CJ-Chen"<notifications@github.com> 
 发送时间: 2019年5月8日(星期三) 上午8:33 
 收件人: "CJ-Chen/TBtools"<TBtools@noreply.github.com>; 
 抄送: "Author"<author@noreply.github.com>;"Clovecookie"<835138001@qq.com>; 
 主题: Re: [CJ-Chen/TBtools] 求0.58版本 (#3) 
 
 
 
 没有。旧的版本或者功能太少，或者含有废弃功能。现在只有最新版

**Comment by fxfish** [comment]
请问GO注释能使用Diamond blastx的结果吗？

**Comment by CJ-Chen** [comment]
可以的。自己转换成query2gi table吧。 
------------------
===============================
CJchenhttp://cj-chen.github.io/


 




------------------ 原始邮件 ------------------
发件人: "fxfish"<notifications@github.com>; 
发送时间: 2019年5月18日(星期六) 晚上6:59
收件人: "CJ-Chen/TBtools"<TBtools@noreply.github.com>; 
抄送: "CJ"<120509419@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [CJ-Chen/TBtools] 求0.58版本 (#3)




请问GO注释能使用Diamond blastx的结果吗？

**Comment by fxfish** [comment]
转换成之后：
TRINITY_DN148674_c0_g1_i1	XP_017729182.1
TRINITY_DN148679_c0_g1_i1	XP_019204186.1
但是有错误，Sorry, annotation failed.

第一项用的是idmapping.tb.gz.DB。

**Comment by JuLianLL** [comment]
请问新版本的circos图怎么保存或导出，窗口底部只有一个save curr setting，circos图怎么导出pdf？
<img width="960" alt="1" src="https://user-images.githubusercontent.com/51206823/58647408-1b3f8400-833a-11e9-949f-07e3d51f95d2.png">

**Comment by CJ-Chen** [comment]
> 请问新版本的circos图怎么保存或导出，窗口底部只有一个save curr setting，circos图怎么导出pdf？
> <img alt="1" width="960" src="https://user-images.githubusercontent.com/51206823/58647408-1b3f8400-833a-11e9-949f-07e3d51f95d2.png">

Ctrl+S 建议加入TBtools使用交流QQ群 交流
