### ISSUE TITLE
下载window的exe文件失败的问题

### ISSUE THREAD

**Issue by Jenny-chen98** [CJ-Chen/TBtools#33]
下载的时候说需要获得授权，请问在哪里能取得授权呢？
![image](https://user-images.githubusercontent.com/59354090/171586718-20b5e000-6475-4222-8d95-510792eb6662.png)

**Comment by CJ-Chen** [comment]
这个百度就可以解决。你就可以授权





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jenny-chen98 ***@***.***&gt;
发送时间: 2022年6月2日 16:19
收件人: CJ-Chen/TBtools ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[CJ-Chen/TBtools] 下载window的exe文件失败的问题 (Issue #33)





 
下载的时候说需要获得授权，请问在哪里能取得授权呢？
