### ISSUE TITLE
expression calculator could not recognize the gene length file

### ISSUE THREAD

**Issue by tinyfallen** [CJ-Chen/TBtools#34]
Hi dear developers,

The expression calculator seems to have some troubles recognizing the gene length file, and I could not find out whether it is a format error of my file or other reasons.

![image](https://user-images.githubusercontent.com/37066354/173524101-43bbb199-1251-493a-a166-58ceb3db9014.png)

Here is my file, looking forward to your reply !

![image](https://user-images.githubusercontent.com/37066354/173523500-abc13452-b347-455b-8654-a0a0a2beb70a.png)

![image](https://user-images.githubusercontent.com/37066354/173523655-1480f3d6-b645-42a4-8053-a3c4ce765f05.png)

**Comment by CJ-Chen** [comment]
Update to the latest verison. 1.098752
