### ISSUE TITLE
最新版本TBtools_windows-x64_1_09876.exe安装闪退问题

### ISSUE THREAD

**Issue by liuxiankai** [CJ-Chen/TBtools#35]
操作系统是Windows 11 专业版
Windows 10 也试过
安装过程中，在这个界面闪退，没有其他提示
![1656342819319](https://user-images.githubusercontent.com/58500378/175974536-7944702d-4dbf-472c-8e1c-3fbb2115b478.png)
尝试了beta版本，可以正常安装

**Comment by CJ-Chen** [comment]
是的，beta版就是要应付一些电脑安全软件。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: liuxiankai ***@***.***&gt;
发送时间: 2022年6月28日 00:35
收件人: CJ-Chen/TBtools ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[CJ-Chen/TBtools] 最新版本TBtools_windows-x64_1_09876.exe安装闪退问题 (Issue #35)





 
操作系统是Windows 11 专业版
 Windows 10 也试过
 安装过程中，在这个界面闪退，没有其他提示
 
 尝试了beta版本，可以正常安装

**Comment by CJ-Chen** [comment]
写兼容版或者win11的话很多人有问题。懒得回答。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: liuxiankai ***@***.***&gt;
发送时间: 2022年6月28日 09:16
收件人: CJ-Chen/TBtools ***@***.***&gt;
抄送: CJ-Chen ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[CJ-Chen/TBtools] 最新版本TBtools_windows-x64_1_09876.exe安装闪退问题 (Issue #35)

**Comment by liuxiankai** [comment]
好的，谢谢
那意思就是beta版本就是解决系统版本/杀毒软件安装问题，功能都是一样的吧

**Comment by Mapaler** [comment]
我一个同事电脑也存在这个问题，UAC都没弹出，但是试了latestJDK就能运行了。
可不可以直接出一个不带JRE的压缩包版本呢？7-zip都无法打开这个exe，但是rar可以改扩展名为zip后打开。

**Comment by CJ-Chen** [comment]
使用 1.113 版本试试。如果确实只有 lastestJDK 可以正常安装，那么就只能是 lastestJDK 了。
具体问题我不太清楚。暂时没找到原因几何。
---
为了保证所有用户的使用环境类似，不会专门出不带JRE的版本。



***@***.***
 
发件人： 枫谷剑仙
发送时间： 2023-02-16 15:55
收件人： CJ-Chen/TBtools
抄送： CJ-Chen; State change
主题： Re: [CJ-Chen/TBtools] 最新版本TBtools_windows-x64_1_09876.exe安装闪退问题 (Issue #35)
我一个同事电脑也存在这个问题，UAC都没弹出，但是试了latestJDK就能运行了。
可不可以直接出一个不带JRE的压缩包版本呢？7-zip都无法打开这个exe，但是rar可以改扩展名为zip后打开。

**Comment by Mapaler** [comment]
> 使用 1.113 版本试试。如果确实只有 lastestJDK 可以正常安装，那么就只能是 lastestJDK 了。 具体问题我不太清楚。暂时没找到原因几何。 --- 为了保证所有用户的使用环境类似，不会专门出不带JRE的版本。 

他是Win11，就是用的1.113的lastestJDK才能运行，其他好多版本都试了不成功。
如果不能专门出无JRE版本，那么可不可以换一个打包器让7zip能直接解压。如果下次遇到所有版本都无法正常执行安装过程，又解压不了，就会遇到阻碍。
![1676534722901_NanaZip](https://user-images.githubusercontent.com/6565860/219304615-c325fe7f-f53e-4b12-88a9-f1a234db81a3.png)

**Comment by CJ-Chen** [comment]
认为无必要，直接lastestJDK.exe 双击安装，应是比用户解压来得合适。



***@***.***
 
发件人： 枫谷剑仙
发送时间： 2023-02-16 16:08
收件人： CJ-Chen/TBtools
抄送： CJ-Chen; State change
主题： Re: [CJ-Chen/TBtools] 最新版本TBtools_windows-x64_1_09876.exe安装闪退问题 (Issue #35)
使用 1.113 版本试试。如果确实只有 lastestJDK 可以正常安装，那么就只能是 lastestJDK 了。 具体问题我不太清楚。暂时没找到原因几何。 --- 为了保证所有用户的使用环境类似，不会专门出不带JRE的版本。
他是Win11，就是用的1.113的lastestJDK才能运行，其他好多版本都试了不成功。
如果不能专门出无JRE版本，那么可不可以换一个打包器让7zip能直接解压。如果下次遇到所有版本都无法正常执行安装过程，又解压不了，就会遇到阻碍。

**Comment by timase2021** [comment]
Hello, please I need help!!!,  I installed TBTools on my windows version V1.113 and try to use eggNOG-mapper helper for my annotation results, only a file filled with results, and it shows this error
 can you help me to solve this problem?
![tbtools-erreur2](https://user-images.githubusercontent.com/87482433/222150001-46af65f4-1ab3-4a22-bfac-cafdef887413.png)

![tbtools-erreur](https://user-images.githubusercontent.com/87482433/222150048-889055a8-44ff-4f8d-8598-919e21da5890.png)
