### ISSUE TITLE
Unable to update the new version

### ISSUE THREAD

**Issue by vinitamehlawat** [CJ-Chen/TBtools#36]
Hi @CJ-Chen 

I `git clone` your repo on my linux mechine. When I tried to run `./Linux.sh` or `java -Xmx2G -jar TBtools_JRE1.6.jar` it is giving error regarding update. I tried to update using `git pull` but it is saying up to date. I am new to github so I am not aware to so many commands. It would be very great help if you could suggest the command to update the latest version.

Thank you
Vinita

**Comment by CJ-Chen** [comment]
try install TBtools from dmg or exe file and extract that jar file.
