### ISSUE TITLE
Not able to run TB-tools

### ISSUE THREAD

**Issue by vinitamehlawat** [CJ-Chen/TBtools#39]
Hi @CJ-Chen 

Thank you for such a wonderful tool. I am quite upset, I downloaded the latest version from releases for linux and whenever I am trying to run it; It showed that author is upset and update to newer version. 

Could you please help me to get the latest version

**Comment by vinitamehlawat** [comment]
Hi @CJ-Chen 

Thank you for the information, But there are only Mac and Windows installer in that link. Could you please suggest anything for linux 

Best 
Vinita

**Comment by CJ-Chen** [comment]
find a pc runing windows or macos. install TBtools. Extract the TBtools_*.jar。And use this jar on linux.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 凌晨4:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CJ-Chen/TBtools] Not able to run TB-tools (Issue #39)





 
Hi @CJ-Chen
 
Thank you for the information, But there are only Mac and Windows installer in that link. Could you please suggest anything for linux
 
Best
 Vinita

**Comment by grzx8888** [comment]
嗨，我现在使用的是最新版的MacOS 13 系统，无法安装tbtools的mac版本，安装界面显示几秒钟便消失了，不知道是软件的问题还是我自己的系统问题呢？

**Comment by CJ-Chen** [comment]
系统问题，是ARM？还是啥？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月9日(星期五) 晚上8:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CJ-Chen/TBtools] Not able to run TB-tools (Issue #39)





 
嗨，我现在使用的是最新版的MacOS 13 系统，无法安装tbtools的mac版本，安装界面显示几秒钟便消失了，不知道是软件的问题还是我自己的系统问题呢？

**Comment by grzx8888** [comment]
您好，是Macbook Pro M1芯片版本。

在今年5月份的时候，还能正常的使用TBTools，最近半年没有用过，今天打开显示版本太旧了，需要更新。
下载最新的版本发现无法安装了。

**Comment by CJ-Chen** [comment]
参考这个链接，更新到最新版本 1.1048 试试看吧。
《TBtools Cookbook》 - 写给「TBtools」所有用户的参考手册 https://www.yuque.com/cjchen/hirv8i
你想知道的，都在里面了：
1. 软件/数据库的下载/更新
2. 对应功能的使用说明与具体示例
3. 常见问题 FAQ 及解决方案
4. 如何有效提出 TBtools 使用问题从而快速获得回复并得到解决

**Comment by CJ-Chen** [comment]
> 
https://musetransfer.com/s/auon2xicb（有效期至12月16日）｜【Muse】你有一份文件待查收，请点击链接获取文件
