### ISSUE TITLE
Circos图的导出问题与文献引用

### ISSUE THREAD

**Issue by JuLianLL** [CJ-Chen/TBtools#4]
你好，请问Circos图如何导出pdf，0.66583版本只看到保存参数按钮，结果如何导出？另外，TBtools里的circos功能与Krzywinski的那篇文献（Circos: an information aesthetic for comparative genomics）有无关系，是否只需引用tbtools的文章即可？

**Comment by CJ-Chen** [comment]
> 你好，请问Circos图如何导出pdf，0.66583版本只看到保存参数按钮，结果如何导出？另外，TBtools里的circos功能与Krzywinski的那篇文献（Circos: an information aesthetic for comparative genomics）有无关系，是否只需引用tbtools的文章即可？

保存图片，直接Control+V 。你的图片中文字有少许重叠，建议调整下字重叠权重，在ControlPanel，欢迎到TBtools使用交流群交流562721348，一般图片画得还不错的，我都会尽快回复
欢迎引用，只需要引用TBtools的bioAxiv文章，与Circos没有关系，TBtools是自己从零实现的Java程序。
