### ISSUE TITLE
About promoter extraction

### ISSUE THREAD

**Issue by ClarenceHsiang** [CJ-Chen/TBtools#41]
Dear Tbtools team,

About the promoter extraction,
I found a problem, when the gene is located at ＋ strand,
the promoter sequence is ok, which ends with ATG
-------------
.......gttcataattaatgtgatatgctgttttactgtgtgttttATGTGTTTGTTAATTTATGG
-------------
However, if the gene is located on - strand,
the promoter sequence seems incorrect as below
------------
.......tctataaatttccttgtcaagcaacaaatggaactcaacaCCCATCTCTCTATGTTTTTC
-----------

Do you have any solution or suggestion?

**Comment by CJ-Chen** [comment]
It should be caused by the mis-annotation in GXF file.
