### ISSUE TITLE
may be tags can be beautifully

### ISSUE THREAD

**Issue by Kiri2002** [CJ-Chen/TBtools#42]
the lastest 4 tags:
1.113
v1.112
1.0987671
1.0987668

how mass! and have error!  1.0987671 > 1,113 !! 
seem you don't know version-num is not decimal!
first it will compare the num before '.', then only compare the num before next '.'
for examlp: 1.113 vs 1.0987671
1st: 1 = 1 
2st: 113 < 0987671 (0 is not be compare, so just 113 < 0987671) !!! that's make wrong!
so many auto get script in linux fail !

and i can't understand, why v1.112 not 1.112 ?????

**Comment by CJ-Chen** [comment]
typo
