### ISSUE TITLE
TBTools eggNOG-mapper helper

### ISSUE THREAD

**Issue by timase2021** [CJ-Chen/TBtools#43]
Hello,

I struggle to analyze my annotation results with eggnog and while reading a publication, I came across TBTools. please I need help with it !!!, I installed TBTools on my windows version V1.113 and try to use eggNOG-mapper helper for my annotation results, only a file filled with results, and it shows this error
can you help me solve this problem?
![tbtools-erreur](https://user-images.githubusercontent.com/87482433/222151000-0c33518e-fb88-466b-a0f7-f6ca63d56c11.png)
![tbtools-erreur2](https://user-images.githubusercontent.com/87482433/222151016-761e8a5f-ef7b-42e3-9041-8e5440442748.png)

**Comment by CJ-Chen** [comment]
发送一下 输入文件给我看看？估计是文件格式的问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月1日(星期三) 晚上9:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [CJ-Chen/TBtools] TBTools eggNOG-mapper helper (Issue #43)





 
Hello,
 
I struggle to analyze my annotation results with eggnog and while reading a publication, I came across TBTools. please I need help with it !!!, I installed TBTools on my windows version V1.113 and try to use eggNOG-mapper helper for my annotation results, only a file filled with results, and it shows this error
 can you help me solve this problem?

**Comment by CJ-Chen** [comment]
没收到。还是直接发送我邮箱吧 ccj0410@gmail.com

**Comment by CJ-Chen** [comment]
一分钟入门并精通TBtools使用。「TBtools技能易物群」解决你所有 TBtools 使用烦恼！
https://www.yuque.com/cjchen/hirv8i/iclxpx2841g205hm
