### ISSUE TITLE
java version in TBtools_windows-x64_1_123.exe is jdk11 rather than the alleged jdk17

### ISSUE THREAD

**Issue by liangjinsong** [CJ-Chen/TBtools#46]
So , errors happens when running TBtools_windows-x64_1_123. The error are as following.

[Debug...All Standard Error Info will show as following:...]
Curr log file:C:\Users\HUAWEI\AppData\Local\Temp\TBtools.4641976879786782117.20230530162712.log
Curr java version:11.0.6
Curr TBtools version:1.123
Maxmum Memory for Curr TBtools: 4127195136
curVersion:1.120:force
Fetch Location:200
inline:## TBtools:Please update to the lastest version (higher than v1.09876). | https://tbtools.cowtransfer.com/s/be6d8daa56df4c
curS:Please update to the lastest version (higher than v1.09876). | https://tbtools.cowtransfer.com/s/be6d8daa56df4c
Factor(>0.6):0.9938803763139422
File Enter:toolsKit.GUItools.DragDropFilePathAndTextPreviewDialogListener@7f43b1c1
Start Drop:java.awt.dnd.DropTargetDropEvent[source=java.awt.dnd.DropTarget@18e9e625]
Process Drop:[java.awt.datatransfer.DataFlavor[mimetype=application/x-java-file-list;representationclass=java.util.List]]
In Drop Processing:java.awt.dnd.DropTargetDropEvent[source=java.awt.dnd.DropTarget@18e9e625]
ARCHAEA_sequence.fasta
Current Count:	1
Finished Drop Processing:java.awt.dnd.DropTargetDropEvent[source=java.awt.dnd.DropTarget@18e9e625]
5月 30, 2023 4:27:49 下午 biocjava.GUIexcutors.BioSoftPipeWrapper.ProtParamWrapperGUIPanel$1$1 run
严重: null
java.lang.NullPointerException
	at GUIbeans.FileAndPasteOutputPanel.fetchOutputFile(FileAndPasteOutputPanel.java:69)
	at biocjava.GUIexcutors.BioSoftPipeWrapper.ProtParamWrapperGUIPanel$1$1.run(ProtParamWrapperGUIPanel.java:49)

**Comment by CJ-Chen** [comment]
latestJDK only available in the *.latestJDK.exe installer.
