### ISSUE TITLE
what's the "Set a file storing domain information in protein coordinate"and "Set a file storing domain information in mRNA coordinate"

### ISSUE THREAD

**Issue by LHXqwq** [CJ-Chen/TBtools#5]
I have tried some projects, you had made a nice app, but some of them i'm dong for first time ,so i don't know what file should i input. If there is any example data ,I'm sure it can be better.thanks

**Comment by CJ-Chen** [comment]
Manual of most function have been shared in QQ group (562721348). 
You could also find examples of them on Wechat ( 生信札记 ).
