### ISSUE TITLE
Error In KEGG enrichment analysis: no information in output

### ISSUE THREAD

**Issue by manoharbisht1998** [CJ-Chen/TBtools#51]
Hey thanks for this comprehensive tool
I am using the KEGG enrichment analysis implemented in TBtools (v1.120) for a non-model organism for which I have non-standard gene ids with types of KO assigned to it. but the final file is creating no information.

Kindly help

**Comment by CJ-Chen** [comment]
Join out slack group for further discussion. https://join.slack.com/t/w1689288812-1ht896372/shared_invite/zt-1z3epmlva-MXKRYrZ3VJxEIsJYpmSMZw
