### ISSUE TITLE
about wgcna shiny

### ISSUE THREAD

**Issue by zhangkunGX** [CJ-Chen/TBtools#52]
在使用tbtools时，有一些疑问，请问大大，新版的tbtools里上传数据没有fpkm这一个数据选项了，是使用count数据进行分析呢，还是把fpkm数据上传，选择某一个特定类型进行分析嘞，希望您有空之余帮学生解惑

**Comment by CJ-Chen** [comment]
自己去看教程吧。一分钟入门并精通TBtools使用。「TBtools技能易物群」解决你所有 TBtools 使用烦恼！
https://www.yuque.com/cjchen/hirv8i/iclxpx2841g205hm
==========
插件视频教程，简单的使用问题，最好到社群讨论
https://www.bilibili.com/video/BV1Qx4y1Q7Ln/?spm_id_from=333.337.search-card.all.click&vd_source=99b311f43b5568699ed1261ca8b64804
