### ISSUE TITLE
cannot display Chinese chars

### ISSUE THREAD

**Issue by littlesulley** [CJ-Chen/TBtools#6]
Hi,
i was using the Heatmap Illustrator which is wonderful for drawing nice heatmaps, but what disappoints is it cannot display Chinese characters normally. Could you tell me how can i set the charset so that non-English chars can be shown? Thanks.

**Comment by CJ-Chen** [comment]
中文字符的显示，或者其他字符，设置字体即可，参考 https://www.jianshu.com/p/3ddb6578d33a

**Comment by littlesulley** [comment]
多谢~
