### ISSUE TITLE
Is it possible to provide the KEGG backend file?

### ISSUE THREAD

**Issue by TypicalSEE** [CJ-Chen/TBtools#7]
Hi, I'm using TBtools to perform KEGG enrichment analysis. But downloading necessary KEGG files always fails. Is it possible to provide the backend file directly? Thanks!

**Comment by CJ-Chen** [comment]
pls join in the user group via https://t.me/joinchat/Q6WHOhWOlHHOkMgRGoN7nw .  Someone will upload it if you ask for it.
