### ISSUE TITLE
KEGG的第一个输入时什么文件，哪里下载

### ISSUE THREAD

**Issue by Trandamere** [CJ-Chen/TBtools#8]
1. A file storing KEGG pathway ontology information. Users could prepare it using the “Make One Backend File From Web” Button.
有了对应号
```
BSU40440	K02314
BSU40480	K03449
BSU40500	K02939
BSU40510	K22927
```
输入了基因
```
BSU40500
```
不能运行，介绍太少了，第一个什么文件，什么格式

**Comment by CJ-Chen** [comment]
直接在 界面上 make a KEGGbackend 即可
