### ISSUE TITLE
HeatMap : Branch Rearrangement 

### ISSUE THREAD

**Issue by venuraherath** [CJ-Chen/TBtools#9]
Hi CJ,

Branches generated by clusters won't flip after clicking flip function.. I am using,  V 1.055
Thank you,
Venura

**Comment by CJ-Chen** [comment]
Well, this function is not fully supported now.

**Comment by venuraherath** [comment]
Thank you, CJ! 
It would be great if you can enable flipping of the very end of branches as well. So far I was successful in flipping branches one level up from the last branches of the cladogram.
